# Generated by Django 4.1.7 on 2023-04-13 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobseeker_image_alter_recruiter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='email_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
