# Generated by Django 4.1.7 on 2023-04-13 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_recruiter_email_token_recruiter_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
