# Generated by Django 4.1.7 on 2023-04-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobseeker_email_token_jobseeker_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='is_verified',
        ),
    ]
