# Generated by Django 4.1.7 on 2023-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
