# Generated by Django 4.1.7 on 2023-04-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
