# Generated by Django 4.1.7 on 2023-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
