# Generated by Django 4.1.7 on 2023-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='catagory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='locations',
            field=models.CharField(max_length=150),
        ),
    ]
